### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by toshibochan** [jamesblanksby/homebridge-gpio#1]
Thanks for plugin! 
You can add time? For example I want GPIO ON 1 second or 15 min!

**Comment by jamesblanksby** [comment]
Thats no problem - I hope you're putting it to good use. Great idea but I am struggling to think of a use case for it. Could you provide me with a couple of real world applications?

**Comment by toshibochan** [comment]
I have a x10 remote control. And I want use relay to connect to remote to control x10 lights. And ceiling fan remote to.

**Comment by toshibochan** [comment]
Other example is I have gate and I want the light stay on 5 min when I open and close the gate

**Comment by Fingerz** [comment]
I would like to use this to control my Somfy motorized roller blinds that currently use an RF remote that can be hacked to wire up the GPIOs from the RaspberryPi to control them...but it needs to be momentary triggers otherwise it will drain the battery of the remote control. Same could be used to control anything with a bush button remote (garage door, motorized awning, etc.).

**Comment by jamesblanksby** [comment]
I will implement some kind of optional timing feature that will allow you to specify how long you wish each pin to stay active. I am short of time this week so hopefully I will get to it this weekend.

**Comment by jamesblanksby** [comment]
See latest [commit](https://github.com/jamesblanksby/homebridge-gpio/commit/967b5d087e95792d4a96675fe6f439428a7c5508).
